import type { Option } from "./types"

const BASE_LOCATIONS: Option[] = [
  { value: "new_york", label: "New York, USA" },
  { value: "los_angeles", label: "Los Angeles, USA" },
  { value: "london", label: "London, UK" },
  { value: "paris", label: "Paris, France" },
  { value: "berlin", label: "Berlin, Germany" },
  { value: "tokyo", label: "Tokyo, Japan" },
  { value: "sydney", label: "Sydney, Australia" },
  { value: "toronto", label: "Toronto, Canada" },
  { value: "mexico_city", label: "Mexico City, Mexico" },
  { value: "guatemala_city", label: "Guatemala City, Guatemala" },
  { value: "panama_city", label: "Panama City, Panama" },
  { value: "san_jose", label: "San José, Costa Rica" },
  { value: "havana", label: "Havana, Cuba" },
  { value: "santo_domingo", label: "Santo Domingo, Dominican Republic" },
  { value: "port_au_prince", label: "Port-au-Prince, Haiti" },
  { value: "kingston", label: "Kingston, Jamaica" },
  { value: "sao_paulo", label: "São Paulo, Brazil" },
  { value: "buenos_aires", label: "Buenos Aires, Argentina" },
  { value: "lima", label: "Lima, Peru" },
  { value: "bogota", label: "Bogotá, Colombia" },
  { value: "santiago", label: "Santiago, Chile" },
  { value: "quito", label: "Quito, Ecuador" },
  { value: "montevideo", label: "Montevideo, Uruguay" },
  { value: "asuncion", label: "Asunción, Paraguay" },
  { value: "la_paz", label: "La Paz, Bolivia" },
  { value: "caracas", label: "Caracas, Venezuela" },
  { value: "madrid", label: "Madrid, Spain" },
  { value: "rome", label: "Rome, Italy" },
  { value: "lisbon", label: "Lisbon, Portugal" },
  { value: "amsterdam", label: "Amsterdam, Netherlands" },
  { value: "brussels", label: "Brussels, Belgium" },
  { value: "zurich", label: "Zurich, Switzerland" },
  { value: "vienna", label: "Vienna, Austria" },
  { value: "warsaw", label: "Warsaw, Poland" },
  { value: "prague", label: "Prague, Czechia" },
  { value: "copenhagen", label: "Copenhagen, Denmark" },
  { value: "oslo", label: "Oslo, Norway" },
  { value: "stockholm", label: "Stockholm, Sweden" },
  { value: "helsinki", label: "Helsinki, Finland" },
  { value: "athens", label: "Athens, Greece" },
  { value: "istanbul", label: "Istanbul, Turkey" },
  { value: "saint_petersburg", label: "Saint Petersburg, Russia" },
  { value: "kyiv", label: "Kyiv, Ukraine" },
  { value: "bucharest", label: "Bucharest, Romania" },
  { value: "budapest", label: "Budapest, Hungary" },
  { value: "sofia", label: "Sofia, Bulgaria" },
  { value: "belgrade", label: "Belgrade, Serbia" },
  { value: "zagreb", label: "Zagreb, Croatia" },
  { value: "dublin", label: "Dublin, Ireland" },
  { value: "tallinn", label: "Tallinn, Estonia" },
  { value: "riga", label: "Riga, Latvia" },
  { value: "vilnius", label: "Vilnius, Lithuania" },
  { value: "shanghai", label: "Shanghai, China" },
  { value: "delhi", label: "Delhi, India" },
  { value: "seoul", label: "Seoul, South Korea" },
  { value: "jakarta", label: "Jakarta, Indonesia" },
  { value: "manila", label: "Manila, Philippines" },
  { value: "bangkok", label: "Bangkok, Thailand" },
  { value: "ho_chi_minh_city", label: "Ho Chi Minh City, Vietnam" },
  { value: "kuala_lumpur", label: "Kuala Lumpur, Malaysia" },
  { value: "singapore", label: "Singapore, Singapore" },
  { value: "hong_kong", label: "Hong Kong, China" },
  { value: "taipei", label: "Taipei, Taiwan" },
  { value: "karachi", label: "Karachi, Pakistan" },
  { value: "dhaka", label: "Dhaka, Bangladesh" },
  { value: "hanoi", label: "Hanoi, Vietnam" },
  { value: "doha", label: "Doha, Qatar" },
  { value: "kuwait_city", label: "Kuwait City, Kuwait" },
  { value: "tel_aviv", label: "Tel Aviv, Israel" },
  { value: "tehran", label: "Tehran, Iran" },
  { value: "dubai", label: "Dubai, UAE" },
  { value: "riyadh", label: "Riyadh, Saudi Arabia" },
  { value: "lagos", label: "Lagos, Nigeria" },
  { value: "cairo", label: "Cairo, Egypt" },
  { value: "johannesburg", label: "Johannesburg, South Africa" },
  { value: "nairobi", label: "Nairobi, Kenya" },
  { value: "casablanca", label: "Casablanca, Morocco" },
  { value: "algiers", label: "Algiers, Algeria" },
  { value: "addis_ababa", label: "Addis Ababa, Ethiopia" },
  { value: "accra", label: "Accra, Ghana" },
  { value: "dar_es_salaam", label: "Dar es Salaam, Tanzania" },
  { value: "tunis", label: "Tunis, Tunisia" },
  { value: "auckland", label: "Auckland, New Zealand" },
  { value: "wellington", label: "Wellington, New Zealand" },
  { value: "suva", label: "Suva, Fiji" },
]

export const DEFAULT_LOCATIONS: Option[] = [...BASE_LOCATIONS].sort((a, b) =>
  a.label.localeCompare(b.label, undefined, { sensitivity: "base" })
)
